version: '3.8'

services:
  api:
    image: mucahitgenc1/formfleks-api:v1.0.0
    container_name: formfleks-api
    restart: always
    ports:
      - "0808:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./uploads:/app/wwwroot/uploads

  ui:
    image: mucahitgenc1/formfleks-base-app-ui:v1.0.0
    container_name: formfleks-ui
    restart: always
    ports:
      - "1608:80"
