// <auto-generated />
using System;
using FormfleksBaseApp.DynamicForms.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormfleksBaseApp.Infrastructure.Migrations.DynamicFormsDb
{
    [DbContext(typeof(DynamicFormsDbContext))]
    partial class DynamicFormsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Admin.QdmsPersonelAktarim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Adi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("adi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departman_Adi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("departman_adi");

                    b.Property<string>("Departman_Kodu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("departman_kodu");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Grup_Kodu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grup_kodu");

                    b.Property<string>("Grup_Kodu_Aciklama")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("grup_kodu_aciklama");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Isyeri_Kodu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("isyeri_kodu");

                    b.Property<string>("Isyeri_Tanimi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("isyeri_tanimi");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_date");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_user_id");

                    b.Property<string>("Pozisyon_Aciklamasi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("pozisyon_aciklamasi");

                    b.Property<string>("Pozisyon_Kodu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pozisyon_kodu");

                    b.Property<string>("Sicil_No")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sicil_no");

                    b.Property<string>("Sirket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sirket");

                    b.Property<string>("Soyadi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("soyadi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ust_Pozisyon_Kodu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ust_pozisyon_kodu");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId");

                    b.HasIndex("Pozisyon_Kodu");

                    b.HasIndex("Sicil_No")
                        .IsUnique();

                    b.HasIndex("Ust_Pozisyon_Kodu");

                    b.ToTable("qdms_personeller", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Admin.QdmsPersonelSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeactivatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("deactivated_count");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("errors_json");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("integer")
                        .HasColumnName("inserted_count");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TriggeredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("updated_count");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.ToTable("qdms_personel_sync_logs", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.FormFieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_key");

                    b.Property<short>("FieldType")
                        .HasColumnType("smallint")
                        .HasColumnName("field_type");

                    b.Property<Guid>("FormTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_type_id");

                    b.Property<string>("HelpText")
                        .HasColumnType("text")
                        .HasColumnName("help_text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("placeholder");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("ValidationRuleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule_json");

                    b.Property<string>("VisibilityRuleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("visibility_rule_json");

                    b.HasKey("Id");

                    b.HasIndex("FormTypeId", "FieldKey")
                        .IsUnique();

                    b.HasIndex("FormTypeId", "SortOrder");

                    b.ToTable("form_fields", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.FormRequestApprovalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("action_at");

                    b.Property<Guid?>("ActionByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_by_user_id");

                    b.Property<string>("ActionComment")
                        .HasColumnType("text")
                        .HasColumnName("action_comment");

                    b.Property<Guid?>("AssigneeRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_role_id");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<long>("ConcurrencyToken")
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_token");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("StepNo")
                        .HasColumnType("integer")
                        .HasColumnName("step_no");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_step_id");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "StepNo");

                    b.HasIndex("Status", "AssigneeRoleId", "AssigneeUserId");

                    b.ToTable("form_request_approvals", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.FormRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("ConcurrencyToken")
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentStepNo")
                        .HasColumnType("integer")
                        .HasColumnName("current_step_no");

                    b.Property<Guid>("FormTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_type_id");

                    b.Property<string>("RequestNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("request_no");

                    b.Property<Guid>("RequestorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requestor_user_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("RequestNo")
                        .IsUnique();

                    b.HasIndex("RequestorUserId", "CreatedAt");

                    b.HasIndex("Status", "CurrentStepNo");

                    b.ToTable("form_requests", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.FormRequestValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_key");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<DateTime?>("ValueDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("value_datetime");

                    b.Property<string>("ValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("value_number");

                    b.Property<string>("ValueText")
                        .HasColumnType("text")
                        .HasColumnName("value_text");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "FieldId")
                        .IsUnique();

                    b.HasIndex("RequestId", "FieldKey");

                    b.ToTable("form_request_values", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.FormSectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FormTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_type_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("FormTypeId", "SortOrder");

                    b.ToTable("form_sections", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.FormTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("AllowedCreateRoleCodesJson")
                        .HasColumnType("text");

                    b.Property<string>("AllowedReportRoleCodesJson")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("form_types", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.UserDelegationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DelegateeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegatee_user_id");

                    b.Property<Guid>("DelegatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegator_user_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("DelegatorUserId");

                    b.HasIndex("DelegatorUserId", "IsActive");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("user_delegations", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.UserLocationRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsGlobalManager")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global_manager");

                    b.Property<string>("LocationName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location_name");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationName");

                    b.HasIndex("UserId", "RoleId");

                    b.ToTable("user_location_roles", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.WorkflowDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FormTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_type_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("FormTypeId", "IsActive");

                    b.HasIndex("FormTypeId", "VersionNo")
                        .IsUnique();

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.DynamicForms.WorkflowStepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowReturnForRevision")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_return_for_revision");

                    b.Property<Guid?>("AssigneeRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_role_id");

                    b.Property<short>("AssigneeType")
                        .HasColumnType("smallint")
                        .HasColumnName("assignee_type");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<string>("DynamicRuleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("dynamic_rule_json");

                    b.Property<short>("FallbackAction")
                        .HasColumnType("smallint")
                        .HasColumnName("fallback_action");

                    b.Property<Guid?>("FallbackUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("fallback_user_id");

                    b.Property<bool>("IsParallel")
                        .HasColumnType("boolean")
                        .HasColumnName("is_parallel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("StepNo")
                        .HasColumnType("integer")
                        .HasColumnName("step_no");

                    b.Property<Guid?>("TargetLocationRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "StepNo")
                        .IsUnique();

                    b.ToTable("workflow_steps", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
