// <auto-generated />
using System;
using FormfleksBaseApp.Infrastructure.Surveys.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormfleksBaseApp.Infrastructure.Migrations.SurveyDb
{
    [DbContext(typeof(SurveyDbContext))]
    [Migration("20260827105426_RemoveSurveyResponseUserId")]
    partial class RemoveSurveyResponseUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SavedAudience", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("AudienceDefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("audience_definition_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("saved_audiences", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("SurveyResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_response_id");

                    b.Property<Guid>("SurveyVersionQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_version_question_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("value_date");

                    b.Property<string>("ValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("value_number");

                    b.Property<string>("ValueText")
                        .HasColumnType("text")
                        .HasColumnName("value_text");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.HasIndex("SurveyVersionQuestionId", "SurveyResponseId");

                    b.ToTable("survey_answers", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyAnswerFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid>("SurveyAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_answer_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SurveyAnswerId");

                    b.ToTable("survey_answer_files", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("CompanySnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("company_snapshot");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DepartmentSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("department_snapshot");

                    b.Property<int>("EmailDeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<string>("EmailErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("EmailRetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_sent_at");

                    b.Property<string>("JobTitleSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("job_title_snapshot");

                    b.Property<DateTime?>("LastEmailAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("location_snapshot");

                    b.Property<string>("ParticipantDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("participant_display_name");

                    b.Property<string>("ParticipantEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("participant_email");

                    b.Property<string>("PersonnelGroupSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("personnel_group_snapshot");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.Property<string>("SnapshotSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("snapshot_source");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("SurveyCampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_campaign_id");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("SurveyCampaignId", "DepartmentSnapshot");

                    b.HasIndex("SurveyCampaignId", "LocationSnapshot");

                    b.HasIndex("SurveyCampaignId", "Status");

                    b.HasIndex("SurveyCampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("survey_assignments", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<Guid?>("BusinessOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_owner_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmailBodyTemplate")
                        .HasColumnType("text")
                        .HasColumnName("email_body_template");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("email_subject");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymous");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("SurveyTemplateVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_template_version_id");

                    b.Property<string>("TargetAudienceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("target_audience_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SurveyTemplateVersionId");

                    b.ToTable("survey_campaigns", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyParticipationGuard", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.HasKey("Token");

                    b.ToTable("survey_participation_guards", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsOtherOption")
                        .HasColumnType("boolean")
                        .HasColumnName("is_other_option");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SurveyVersionQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_version_question_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("SurveyVersionQuestionId");

                    b.ToTable("survey_question_options", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("CompanySnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("company_snapshot");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DepartmentSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("department_snapshot");

                    b.Property<string>("JobTitleSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("job_title_snapshot");

                    b.Property<string>("LocationSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("location_snapshot");

                    b.Property<string>("PersonnelGroupSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("personnel_group_snapshot");

                    b.Property<string>("ReceiptCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SurveyAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_assignment_id");

                    b.Property<Guid>("SurveyCampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_campaign_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SurveyAssignmentId");

                    b.HasIndex("SurveyCampaignId", "DepartmentSnapshot");

                    b.HasIndex("SurveyCampaignId", "LocationSnapshot");

                    b.HasIndex("SurveyCampaignId", "SubmittedAt");

                    b.ToTable("survey_responses", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyResultViewer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("access_level");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<Guid>("SurveyCampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_campaign_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("SurveyCampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("survey_result_viewers", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyTempFileUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Token", "QuestionId", "StorageKey");

                    b.ToTable("survey_temp_file_uploads", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("DefaultIsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("default_is_anonymous");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("survey_templates", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<Guid>("SurveyTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_template_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("SurveyTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("survey_template_versions", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyVersionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<short>("QuestionType")
                        .HasColumnType("smallint")
                        .HasColumnName("question_type");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SurveyVersionSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_version_section_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VisibilityRuleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("visibility_rule_json");

                    b.HasKey("Id");

                    b.HasIndex("SurveyVersionSectionId");

                    b.ToTable("survey_version_questions", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyVersionSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SurveyTemplateVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_template_version_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SurveyTemplateVersionId");

                    b.ToTable("survey_version_sections", (string)null);
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyAnswer", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyResponse", "SurveyResponse")
                        .WithMany("Answers")
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyVersionQuestion", "SurveyVersionQuestion")
                        .WithMany()
                        .HasForeignKey("SurveyVersionQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SurveyResponse");

                    b.Navigation("SurveyVersionQuestion");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyAnswerFile", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyAnswer", "SurveyAnswer")
                        .WithMany("Files")
                        .HasForeignKey("SurveyAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyAnswer");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyAssignment", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyCampaign", "SurveyCampaign")
                        .WithMany("Assignments")
                        .HasForeignKey("SurveyCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyCampaign");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyCampaign", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyTemplateVersion", "SurveyTemplateVersion")
                        .WithMany("Campaigns")
                        .HasForeignKey("SurveyTemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SurveyTemplateVersion");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyQuestionOption", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyVersionQuestion", "SurveyVersionQuestion")
                        .WithMany("Options")
                        .HasForeignKey("SurveyVersionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyVersionQuestion");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyResponse", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyAssignment", "SurveyAssignment")
                        .WithMany()
                        .HasForeignKey("SurveyAssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyCampaign", "SurveyCampaign")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyAssignment");

                    b.Navigation("SurveyCampaign");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyResultViewer", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyCampaign", "SurveyCampaign")
                        .WithMany("ResultViewers")
                        .HasForeignKey("SurveyCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyCampaign");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyTemplateVersion", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyTemplate", "SurveyTemplate")
                        .WithMany("Versions")
                        .HasForeignKey("SurveyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyTemplate");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyVersionQuestion", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyVersionSection", "SurveyVersionSection")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyVersionSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyVersionSection");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyVersionSection", b =>
                {
                    b.HasOne("FormfleksBaseApp.Domain.Entities.Surveys.SurveyTemplateVersion", "SurveyTemplateVersion")
                        .WithMany("Sections")
                        .HasForeignKey("SurveyTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyTemplateVersion");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyAnswer", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyCampaign", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Responses");

                    b.Navigation("ResultViewers");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyTemplateVersion", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyVersionQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("FormfleksBaseApp.Domain.Entities.Surveys.SurveyVersionSection", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
